### ISSUE TITLE
cross-compile bully for OpenWrt (barrier_breaker)

### ISSUE THREAD

**Issue by micsutka** [Lrs121/bully#1]
Hi,

I can cross-compile the source code without any error via OpenWrt SDK.
After copying and installing the ipk, then running the "bully -b XX:XX:XX:XX:XX mon0", it stops with:
[!] Bully v1.0-22 - WPS vulnerability assessment utility
[!] ioctl(SIOCGIWFREQ) on 'mon0' failed with '0'
[!] Using 'xx:xx:xx:xx:xx:xx' for the source MAC address
[+] Datalink type set to '127', radiotap headers present
[+] Scanning for beacon from 'xx:xx:xx:xx:xx:xx' on channel 'unknown'
[+] Got beacon for 'yyyyyyy' (xx:xx:xx:xx:xx:xx)
[+] Switching interface 'mon0' to channel '7'
[!] ioctl(SIOCSIWFREQ) on 'mon0' failed with '-1'
[X] Unable to set channel on 'mon0', exiting

I've switched the wifi to monitor mode via: "airmon-ng start wlan0"
The "airodump-ng mon0" command works great.
My router is D-Link DIR-825, so I'm using this SDK:
https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2

What could be the problem?
Thanks!
micsu

**Comment by Lrs121** [comment]
From what I've read, the reason it might not able to change the channel on mon0 is because the original interface, e.g. wlan0, might still be up and possibly being used.

Try doing OpenWrt's equivalent of running "ifconfig wlan0 down" then try to see if bully works.

Also, check to make sure that nothing brings the wlan0 interface back up automatically.
For example, in Ubuntu you have to run "service network-manager stop" or else the network manager service will bring wlan0 back up.

Sources
https://forums.hak5.org/index.php?/topic/30521-reaver-on-the-mark-v/page-3#entry245470
https://forums.hak5.org/index.php?/topic/30521-reaver-on-the-mark-v/page-3#entry245471
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=83343

**Comment by micsutka** [comment]
Thank you very much for your help!
Running "ifconfig wlan0 down" has solved the problem, now bully works on OpenWrt!

Additionally I had to extend supported channels for 2.4ghz (channel 12 and channel 13) based on this:
https://github.com/HorayNarea/bully/commit/d37e7e61eb2ccf1277d6accd0af8fcdb70a94a4a

**Comment by Lrs121** [comment]
You are welcome. Also thank you for including the link I'll add those channels in as soon as I get the chance.
